Added the host entries for each vagrant machine to dev-dependencies

diff --git a/dev-dependencies b/dev-dependencies
--- a/dev-dependencies
+++ b/dev-dependencies
@@ -1,5 +1,21 @@
 #!/bin/bash
+
+set -e
+
+function add-to-hosts {
+    if ! grep --quiet $1 /etc/hosts; then 
+      echo "$2 $1 is missing in /etc/hosts - adding it"
+      echo "$2    $1" >> /etc/hosts
+    fi
+}
+
+add-to-hosts "stackstorm-master" "192.168.42.42"
+add-to-hosts "testtank1" "192.168.42.43"
+
 if ! vagrant plugin list | grep --quiet vagrant-hostmanager; then 
-  echo "The vagrant package vagrant-hostmanager is missing"
-  vagrant plugin install vagrant-hostmanager
+    echo "The vagrant package vagrant-hostmanager is missing"
+    vagrant plugin install vagrant-hostmanager
+else
+    echo "vagrant-hostmanager is already installed"
 fi 
+
